version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"
    volumes:
      - ./consignment-cli/consignment.json:/app/consignment.json
      - ./consignment-cli/consignment-cli:/app/consignment-cli
    depends_on:
      - consignment-service

  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"
    volumes:
      - ./user-cli/user-cli:/app/user-cli
    depends_on:
      - user-service

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    volumes:
      - ./consignment-servicecli/consignment-service:/app/consignment-service
    depends_on:
      - datastore
      - vessel-service

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    volumes:
      - ./vessel-service/vessel-service:/app/vessel-service
    depends_on:
      - datastore

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    volumes:
      - ./user-service/user-service:/app/user-service
    depends_on:
      - database

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432
