version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on:
      - consignment-service

  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on:
      - user-service

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    depends_on:
      - datastore
      - vessel-service

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    depends_on:
      - datastore

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database
      - nats

  email-service:
    build: ./email-service
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats:4222"
    depends_on:
      - nats

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432

  nats:
    image: nats
    ports:
      - 8222:8222
      - 6222:6222
      - 4222:4222
