apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: greeter-svc
  labels:
    deployment: greeter-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-svc
  template:
    metadata:
      labels:
        app: greeter-svc        
    spec:
      containers:
      - name: greeter-svc
        image: gcr.io/rugged-memory-205712/greeter-k8s-server:124
        imagePullPolicy: Always
        command: [
          "./server",
        ]
        env:        
        - name: MICRO_REGISTRY
          value: "kubernetes"